"""Internal contract for execution providers."""

from collections.abc import Iterator
from typing import Protocol

from celesto._connection_info import DisplayMode
from celesto._terminal import TerminalConnection
from celesto.types import (
    BrowserConnection,
    CommandEvent,
    CommandResult,
    DisplayConnection,
    PublishedPort,
)


class ComputerProvider(Protocol):
    @property
    def id(self) -> str | None: ...
    def start(self) -> None: ...
    def attach(self, computer_id: str) -> None: ...
    def validate_command(self, command: str, timeout: int) -> None: ...
    def validate_terminal(self, terminal_id: str | None) -> None: ...
    def validate_ports(self) -> None: ...
    def run(self, command: str, timeout: int) -> CommandResult: ...
    def run_stream(self, command: str, timeout: int) -> Iterator[CommandEvent]: ...
    def terminal(self, *, terminal_id: str | None) -> TerminalConnection: ...
    def browser(self) -> BrowserConnection: ...
    def display(self, *, mode: DisplayMode) -> DisplayConnection: ...
    def publish_port(self, port: int) -> PublishedPort: ...
    def published_ports(self) -> list[PublishedPort]: ...
    def unpublish_port(self, port: int) -> PublishedPort: ...
    def delete(self) -> None: ...
    def close(self) -> None: ...
